### ISSUE TITLE
Error when inserting a new record in a HSQLDB Server database using GUI

### ISSUE THREAD

**Issue by rigo** [prrvchr/jdbcDriverOOo#3]
When I try to insert a new record in a table (setting values only for the required fields -4-) using LO Base's GUI  (Windows 10 Version: 7.4.6.2 (x64)) selecting Tables and then opening the table, connected to a database managed by an  HSQLDB Server (version 2.7.2 same OS) the following error is displayed:

SQL State 24515 error code -3606 incorrect cursor state all columns must be set before calling INSERT

However, when I perform the same operation just changing LO Base's file connection type to JDBC (driver version 2.7.2) the record is added successfully.

So apparently changing LO's Base connection type to JDBC is causing non required fields to be set null values before the INSERT operation takes place.

**Comment by rigo** [comment]
Never mind. Apparently it's an issue with either HSQLDB or LOB and AOO. For more information please see:

[https://forum.openoffice.org/en/forum/viewtopic.php?t=106762](https://forum.openoffice.org/en/forum/viewtopic.php?t=106762)

[https://bugs.documentfoundation.org/show_bug.cgi?id=146568](https://bugs.documentfoundation.org/show_bug.cgi?id=146568)

**Comment by prrvchr** [comment]
Hi rigo,

> SQL State 24515 error code -3606 incorrect cursor state all columns must be set before calling INSERT

If bookmark mode is validated then it seems to me that it is necessary to fill all the columns when inserting a new row in a table.

If you deactivate the use of bookmarks, by: **Tools -> Options -> Base drivers -> JDBC driver -> UNO driver setting -> Use bookmarks**
Then it should be possible not to fill in the columns which have a default value.

For me this problem is linked to poor use of bookmarks by Base...
